baseURL: "https://vdlad.github.io/" 
title: Vedang Lad
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        # - name: Courses
        #   url: /courses/
        #   weight: 2
        # - name: Design
        #   url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 2     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Master's student at MIT in the Tegmark AI Safety Group where I study mechanastic interpretability."
    author: Vedang Lad
    googleAnalyticsID: "G-3MZYQN070Y"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Vedang Lad
          subtitle: "I am currently a Master's student at MIT under the guidance of Max Tegmark within the Tegmark AI Safety Group. My research centers on the mechanistic interpretability of deep learning models. During my undergraduate studies at MIT, I double-majored in Computer Science and Physics, where my research primarily focused on intuitive physics, computer vision, and data-centric AI."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Vedang Lad
          buttons:
            - name: Papers
              url: /papers/
            # - name: Courses
            #   url: /courses/
            # - name: Design
            #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:vedang@mit.edu
        # - name: Location
        #   url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=-zikf2wAAAAJ&hl=en&oi=ao
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/vdlad

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Vedang Lad"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
