baseURL: "http://www.vedanglad.com/" 
title: Vedang Lad
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Projects
          url: /projects/
        #   weight: 2
        # - name: Design
        #   url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 2     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I was previously a Master's student at MIT in the Tegmark AI Safety Group where I studied mechanistic interpretability."
    author: Vedang Lad
    googleAnalyticsID: "G-3MZYQN070Y"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false 
    math: true
    profileMode:
          enabled: true
          title: Vedang Lad
          subtitle: |
            <div style="text-align: left; font-size: 1.2em; line-height: 1.6em; margin-top: 20px;">
              <strong>Welcome to my corner of the internet!</strong> <br><br>

              I am currently an independent researcher working on LLM interpretability. 
              Previously, I was a Master’s student at MIT under the guidance of <a href="https://tegmark.org/" target="_blank">Max Tegmark</a>. 
              I deeply believe that enhancing the interpretability of deep learning models is crucial for the development and deployment of safe AI systems. 🤖 <br><br>

              During my years at MIT, I pursued a double major in Computer Science and Physics 
              while also being a NCAA collegiate cross country and track and field athlete. 🏃‍♂️ <br><br>

              <em>Please email me if there is something I can do for you! 😊</em>
            </div>


          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Vedang Lad
          buttons:
            - name: Papers
              url: /papers/
            - name: Projects
              url: /projects/
            # - name: Design
            #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:vedanglad@stanford.edu
        # - name: Location
        #   url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=-zikf2wAAAAJ&hl=en&oi=ao
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/vdlad
        - name: Strava
          url: https://www.strava.com/athletes/16214836

        

    assets:
        disableHLJS: true
        disableScrollBarStyle: false
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Vedang Lad"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
