baseURL: "http://www.vedanglad.com/" 
title: Vedang Lad
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Projects
          url: /projects/
        #   weight: 2
        # - name: Design
        #   url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 2     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Master's student at MIT in the Tegmark AI Safety Group where I study mechanistic interpretability."
    author: Vedang Lad
    googleAnalyticsID: "G-3MZYQN070Y"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Vedang Lad
          subtitle: "I am currently an independent researcher in the MATS program working on LLM interpretability. Previously I was a Master's student at MIT, working under the guidance of Max Tegmark within the Tegmark AI Safety Group. My research is centered on enhancing the interpretability of deep learning models to enable the development and deployment of safe AI systems. During my undergraduate years at MIT, I pursued a double major in Computer Science and Physics, with a primary focus on computer vision research. In my freetime I like to run, paint, and take photos 😊 "
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Vedang Lad
          buttons:
            - name: Papers
              url: /papers/
            - name: Projects
              url: /projects/
            # - name: Design
            #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:vedang@mit.edu
        # - name: Location
        #   url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=-zikf2wAAAAJ&hl=en&oi=ao
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/vdlad
        - name: Strava
          url: https://www.strava.com/athletes/16214836

        

    assets:
        disableHLJS: true
        disableScrollBarStyle: false
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Vedang Lad"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
